# file for music list

# contains dictionary of song and their location
eng_music = {
    "alone" : r"D:\songs\Music(eng)\Alone, Pt. II.mp3",
    "bad boy" : r"D:\songs\Music(eng)\Bad Boy (feat. Luana Kiara).mp3",
    "believer" : r"D:\songs\Music(eng)\Believer.mp3",
    "bilionera" : r"D:\songs\Music(eng)\Bilionera.mp3",
    "bones" : r"D:\songs\Music(eng)\Bones.mp3",
    "cold" : r"D:\songs\Music(eng)\Cold.mp3",
    "criminal" : r"D:\songs\Music(eng)\Criminal.mp3",
    "cupid" : r"D:\songs\Music(eng)\Cupid - Twin Ver..mp3",
    "danza kuduro" : r"D:\songs\Music(eng)\Danza Kuduro.mp3",
    "fast and furious" : r"D:\songs\Music(eng)\Danza Kuduro.mp3",
    "enemy" : r"D:\songs\Music(eng)\Enemy (with JID) - from the series Arcane League of Legends.mp3",
    "faded" : r"D:\songs\Music(eng)\Faded.mp3",
    "falling" : r"D:\songs\Music(eng)\Falling.mp3",
    "fearless" : r"D:\songs\Music(eng)\Fearless Pt. II.mp3",
    "fight back" : r"D:\songs\Music(eng)\Fight Back.mp3",
    "gangsta's paradise" : r"D:\songs\Music(eng)\Gangsta's Paradise.mp3",
    "gangsta" : r"D:\songs\Music(eng)\Gangsta.mp3",
    "go down deh" : r"D:\songs\Music(eng)\Go Down Deh (feat. Shaggy and Sean Paul).mp3",
    "grateful" : r"D:\songs\Music(eng)\Grateful.mp3",
    "happy nation" : r"D:\songs\Music(eng)\Happy Nation.mp3",
    "hey mama" : r"D:\songs\Music(eng)\Hey Mama (feat. Nicki Minaj, Bebe Rexha & Afrojack).mp3",
    "hymn for the weekend" : r"D:\songs\Music(eng)\Hymn for the Weekend.mp3",
    "industry baby" : r"D:\songs\Music(eng)\INDUSTRY BABY (feat. Jack Harlow).mp3",
    "infinity" : r"D:\songs\Music(eng)\Infinity.mp3",
    "let me down slowly" : r"D:\songs\Music(eng)\Let Me Down Slowly.mp3",
    "lovely" : r"D:\songs\Music(eng)\lovely (with Khalid).mp3",
    "maniac" : r"D:\songs\Music(eng)\Maniac.mp3",
    "no lie" : r"D:\songs\Music(eng)\No Lie.mp3",
    "on my way" : r"D:\songs\Music(eng)\On My Way.mp3",
    "panama" : r"D:\songs\Music(eng)\Panama.mp3",
    "rise up" : r"D:\songs\Music(eng)\Rise Up.mp3",
    "rockstar" : r"D:\songs\Music(eng)\Rockstar.mp3",
    "safari" : r"D:\songs\Music(eng)\Safari.mp3",
    "soldier" : r"D:\songs\Music(eng)\Soldier.mp3",
    "stay" : r"D:\songs\Music(eng)\STAY (with Justin Bieber).mp3",
    "sugar and brownies" : r"D:\songs\Music(eng)\Sugar & Brownies.mp3",
    "superhero" : r"D:\songs\Music(eng)\Superhero.mp3",
    "the box" : r"D:\songs\Music(eng)\The Box.mp3",
    "the nights" : r"D:\songs\Music(eng)\The Nights.mp3",
    "unstoppable" : r"D:\songs\Music(eng)\Unstoppable.mp3",
    "детство" : r"D:\songs\Music(eng)\Детство.mp3",
    "childhood" : r"D:\songs\Music(eng)\Детство.mp3",
}